using AutoMapper;
using NexusFlow.Application.DTOs.Auth;
using NexusFlow.Domain.Entities;

namespace NexusFlow.Application.Mappings
{
    public class AuthProfile : Profile
    {
        public AuthProfile()
        {
            // Maps the user fields only — AccessToken, RefreshToken and
            // AccessTokenExpiry are generated by IJwtTokenService and must
            // be set on the returned DTO after mapping.
            CreateMap<User, AuthResponseDto>()
                .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.Role, opt => opt.MapFrom(src => src.Role.ToString()))
                .ForMember(dest => dest.AccessToken, opt => opt.Ignore())
                .ForMember(dest => dest.RefreshToken, opt => opt.Ignore())
                .ForMember(dest => dest.AccessTokenExpiry, opt => opt.Ignore());
        }
    }
}